# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqeXpG4ULTldbhmiJiObimWQkNHvnFYx
"""

def kasalliklar_tashxisi(belgi):
  if belgi=="tomog' og'rig'i":
    return"Ambraksol iching"
  elif belgi=="lab yorilishi":
     return"oq pamada surting"
  elif belgi=="Oshqozon og'rishi":
      return"Noshpa iching"
  elif belgi=="Ko'z yoshlanishi":
      return"Kon'unktivit tomizing"
  elif belgi=="Quloq yallig'lanishi":
      return"Otitis tomizing"
  elif belgi=="Yurakka kislorod yetishmasligi":
      return"Angina pektoris iching"
  elif belgi=="Oyoq og'rig'i":
      return"Osteoartrit surting"
  elif belgi=="Bosh og'rig'i":
      return"Tension iching"
  elif belgi=="Tish og'rig'i":
      return"bolnol iching"
  elif belgi=="Allergiya bo'lsa":
      return"Antihistaminlar iching"
  else:
        return "SHifokor Muslimabonuga murojaat qiling"
  belgi=input("Kasallik belgisini kiriting")
  natija=kasallik_tashxisi(belgi)
  print(natija)